---
docker_edition: 'ce'
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
  - "containerd.io"
docker_packages_state: present

# Service options.
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true

# Docker Compose Plugin options.
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "v2.11.1"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}"
docker_compose_path: /usr/local/bin/docker-compose

# Enable repo setup
docker_add_repo: true
docker_raspbian_gpg_key_path: /etc/apt/keyrings/docker.gpg
docker_raspbian_gpg_url: https://download.docker.com/linux/raspbian/gpg

# Docker repo URL.
docker_repo_url: https://download.docker.com/linux

# Used only for RedHat.
docker_yum_repo_url: "{{ docker_repo_url }}/rhel/docker-{{ docker_edition }}.repo"
docker_yum_gpg_key: "{{ docker_repo_url }}/rhel/gpg"

# A list of users who will be added to the docker group.
docker_users: []

# Docker daemon options as a dict
docker_daemon_options: {}
