---
- name: Debug variable
  debug:
    var: k3s_installation_path

- name: Download installation script
  get_url:
    url: "{{ installation_script_url }}"
    dest: "{{ installation_script_path }}"
    mode: 0655

- name: Get info about directory
  command: ls -ltra /tmp
  
- name: Install k3s
  command: "{{ installation_script_path }}"
