---
- name: Check if k3s is installed
  systemd:
    name: k3s
    state: started
  register: k3s_service_status
  ignore_errors: true

- include_tasks: k3s-install.yaml
  when: not k3s_service_status | bool

- name: Ensure that k3s in enabled at boot
  service:
    name: k3s
    state: started
    enabled: true
  ignore_errors: true
