---
- name: Ensure old versions of Docker are not installed.
  package: 
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present
  when: docker_add_repo | bool

- name: Add Docker repository.
  template:
    src: templates/docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  when: docker_add_repo | bool

- name: Print Docker yum repo
  debug:
    msg: "YUM REPO: {{ docker_yum_repo_url }}"

- name: Configure containerd on Rocky 9.
  block:
    - name: Ensure container-selinux is installed.
      package:
        name: container-selinux
        state: present

    - name: Ensure containerd.io is installed.
      package:
        name: containerd.io
        state: present
  when: ansible_distribution_major_version | int == 9

